# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/common/attributes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aio/common/attributes.proto\x12\x02io*\xe4\x01\n\x10\x44\x65viceAttributes\x12\x10\n\x0cNoAttributes\x10\x00\x12\x07\n\x03Ios\x10\x01\x12\x0b\n\x07\x41ndroid\x10\x02\x12\x11\n\rSupportWallet\x10\x04\x12\x11\n\rWalletScanner\x10\x08\x12\x10\n\x0cWalletDaemon\x10\x10\x12\x10\n\x0cWalletPasses\x10 \x12\x0b\n\x07Windows\x10@\x12\x08\n\x03OSX\x10\x80\x01\x12\n\n\x05Linux\x10\x80\x02\x12\x0b\n\x06Mobile\x10\x80\x04\x12\x0c\n\x07\x44\x65sktop\x10\x80\x08\x12\x0b\n\x06Tablet\x10\x80\x10\x12\x13\n\x0eUnsupportedIos\x10\x80 BG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.common.attributes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _DEVICEATTRIBUTES._serialized_start=35
  _DEVICEATTRIBUTES._serialized_end=263
# @@protoc_insertion_point(module_scope)
