# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/expiry.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'io/common/expiry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passkit_io.common import common_objects_pb2 as io_dot_common_dot_common__objects__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16io/common/expiry.proto\x12\x02io\x1a\x1eio/common/common_objects.proto\"\x84\x01\n\x0e\x45xpirySettings\x12\"\n\nexpiryType\x18\x01 \x01(\x0e\x32\x0e.io.ExpiryType\x12#\n\x0f\x66ixedExpiryDate\x18\x02 \x01(\x0b\x32\x08.io.DateH\x00\x12\x1a\n\x10\x65xpireAfterXDays\x18\x03 \x01(\rH\x00\x42\r\n\x0b\x65xpiryOneof*\x8a\x01\n\nExpiryType\x12\x0f\n\x0b\x45XPIRE_NONE\x10\x00\x12\x18\n\x14\x45XPIRE_ON_FIXED_DATE\x10\x01\x12\x17\n\x13\x45XPIRE_AFTER_X_DAYS\x10\x02\x12 \n\x1c\x45XPIRE_ON_VARIABLE_DATE_TIME\x10\x03\x12\x16\n\x12\x45XPIRE_SET_TO_NULL\x10\x04\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.common.expiry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _globals['_EXPIRYTYPE']._serialized_start=198
  _globals['_EXPIRYTYPE']._serialized_end=336
  _globals['_EXPIRYSETTINGS']._serialized_start=63
  _globals['_EXPIRYSETTINGS']._serialized_end=195
# @@protoc_insertion_point(module_scope)
