# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/localization.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'io/common/localization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/common/localization.proto\x12\x02io\"\x83\x01\n\x0fLocalizedString\x12;\n\x0ctranslations\x18\x01 \x03(\x0b\x32%.io.LocalizedString.TranslationsEntry\x1a\x33\n\x11TranslationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x97\x03\n\x0cLanguageCode\x12\x06\n\x02\x45N\x10\x00\x12\x06\n\x02\x41R\x10\x04\x12\x0b\n\x07ZH_HANS\x10\x08\x12\x0b\n\x07ZH_HANT\x10\x0c\x12\t\n\x05ZH_HK\x10\x10\x12\x06\n\x02\x43\x41\x10\x14\x12\x06\n\x02HR\x10\x18\x12\x06\n\x02\x43S\x10\x1c\x12\x06\n\x02\x44\x41\x10 \x12\x06\n\x02\x44\x45\x10$\x12\t\n\x05\x45N_AU\x10(\x12\t\n\x05\x45N_GB\x10,\x12\t\n\x05\x45N_CA\x10\x30\x12\t\n\x05\x45N_US\x10\x34\x12\t\n\x05\x45N_IN\x10\x38\x12\x06\n\x02\x45S\x10<\x12\n\n\x06\x45S_419\x10@\x12\x06\n\x02\x46I\x10\x44\x12\x06\n\x02\x46R\x10H\x12\t\n\x05\x46R_CA\x10L\x12\x06\n\x02\x45L\x10P\x12\x06\n\x02HE\x10T\x12\x06\n\x02HI\x10X\x12\x06\n\x02HU\x10\\\x12\x06\n\x02ID\x10`\x12\x06\n\x02IT\x10\x64\x12\x06\n\x02JA\x10h\x12\x06\n\x02KO\x10l\x12\x06\n\x02MS\x10p\x12\x06\n\x02MT\x10t\x12\x06\n\x02NL\x10x\x12\x06\n\x02NB\x10|\x12\x07\n\x02PL\x10\x80\x01\x12\x07\n\x02PT\x10\x84\x01\x12\n\n\x05PT_BR\x10\x88\x01\x12\x07\n\x02RO\x10\x8c\x01\x12\x07\n\x02RU\x10\x90\x01\x12\x07\n\x02SK\x10\x94\x01\x12\x07\n\x02SV\x10\x98\x01\x12\x07\n\x02TH\x10\x9c\x01\x12\x07\n\x02TR\x10\xa0\x01\x12\x07\n\x02UK\x10\xa4\x01\x12\x07\n\x02VI\x10\xa8\x01\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.common.localization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _globals['_LOCALIZEDSTRING_TRANSLATIONSENTRY']._loaded_options = None
  _globals['_LOCALIZEDSTRING_TRANSLATIONSENTRY']._serialized_options = b'8\001'
  _globals['_LANGUAGECODE']._serialized_start=171
  _globals['_LANGUAGECODE']._serialized_end=578
  _globals['_LOCALIZEDSTRING']._serialized_start=37
  _globals['_LOCALIZEDSTRING']._serialized_end=168
  _globals['_LOCALIZEDSTRING_TRANSLATIONSENTRY']._serialized_start=117
  _globals['_LOCALIZEDSTRING_TRANSLATIONSENTRY']._serialized_end=168
# @@protoc_insertion_point(module_scope)
