# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/common/proximity.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'io/common/proximity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passkit_io.common import localization_pb2 as io_dot_common_dot_localization__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19io/common/proximity.proto\x12\x02io\x1a\x1cio/common/localization.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa7\x03\n\x06\x42\x65\x61\x63on\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1b\n\x05major\x18\x04 \x01(\rB\x0c\x92\x41\tY\x00\x00\x00\x00\xe0\xff\xef@\x12\x1b\n\x05minor\x18\x05 \x01(\rB\x0c\x92\x41\tY\x00\x00\x00\x00\xe0\xff\xef@\x12\x19\n\x11lockScreenMessage\x18\x06 \x01(\t\x12\x37\n\x1alocalizedLockScreenMessage\x18\x07 \x01(\x0b\x32\x13.io.LocalizedString\x12\x10\n\x08position\x18\x08 \x01(\r:\xd4\x01\x92\x41\xd0\x01\n\xcd\x01*\x06\x42\x65\x61\x63on2\xa7\x01\x41 beacon record enables the pass to push a message to the lock screen when the user is in close proximity with the beacon. Beacons are currently only supported by iOS.\xd2\x01\x04uuid\xd2\x01\x11lockScreenMessage\"\x94\x03\n\x0bGPSLocation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x05 \x01(\x05\x12\x19\n\x11lockScreenMessage\x18\x06 \x01(\t\x12\x37\n\x1alocalizedLockScreenMessage\x18\x07 \x01(\x0b\x32\x13.io.LocalizedString\x12\x10\n\x08position\x18\x08 \x01(\r:\xdd\x01\x92\x41\xd9\x01\n\xd6\x01*\x0cGPS Location2\xa4\x01\x41 location record enables the pass to be pushed to the lock screen when the user is in near the location. For iOS users, a customized message can also be displayed.\xd2\x01\x03lat\xd2\x01\x04long\xd2\x01\x11lockScreenMessage\"!\n\x0cRelevantDate\x12\x11\n\ttimestamp\x18\x01 \x01(\rBG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.common.proximity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _globals['_BEACON'].fields_by_name['major']._loaded_options = None
  _globals['_BEACON'].fields_by_name['major']._serialized_options = b'\222A\tY\000\000\000\000\340\377\357@'
  _globals['_BEACON'].fields_by_name['minor']._loaded_options = None
  _globals['_BEACON'].fields_by_name['minor']._serialized_options = b'\222A\tY\000\000\000\000\340\377\357@'
  _globals['_BEACON']._loaded_options = None
  _globals['_BEACON']._serialized_options = b'\222A\320\001\n\315\001*\006Beacon2\247\001A beacon record enables the pass to push a message to the lock screen when the user is in close proximity with the beacon. Beacons are currently only supported by iOS.\322\001\004uuid\322\001\021lockScreenMessage'
  _globals['_GPSLOCATION']._loaded_options = None
  _globals['_GPSLOCATION']._serialized_options = b'\222A\331\001\n\326\001*\014GPS Location2\244\001A location record enables the pass to be pushed to the lock screen when the user is in near the location. For iOS users, a customized message can also be displayed.\322\001\003lat\322\001\004long\322\001\021lockScreenMessage'
  _globals['_BEACON']._serialized_start=112
  _globals['_BEACON']._serialized_end=535
  _globals['_GPSLOCATION']._serialized_start=538
  _globals['_GPSLOCATION']._serialized_end=942
  _globals['_RELEVANTDATE']._serialized_start=944
  _globals['_RELEVANTDATE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
