# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/event_tickets/venue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from io.common import localization_pb2 as io_dot_common_dot_localization__pb2
from io.common import proximity_pb2 as io_dot_common_dot_proximity__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/event_tickets/venue.proto\x12\revent_tickets\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cio/common/localization.proto\x1a\x19io/common/proximity.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa4\x03\n\x05Venue\x12\x11\n\x02id\x18\x01 \x01(\tB\x05\x92\x41\x02@\x01\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12*\n\rlocalizedName\x18\x04 \x01(\x0b\x32\x13.io.LocalizedString\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12-\n\x10localizedAddress\x18\x06 \x01(\x0b\x32\x13.io.LocalizedString\x12\x10\n\x08timezone\x18\x07 \x01(\t\x12\"\n\tgpsCoords\x18\x08 \x03(\x0b\x32\x0f.io.GPSLocation\x12\x32\n\x07\x63reated\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x05\x92\x41\x02@\x01\x12\x32\n\x07updated\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x05\x92\x41\x02@\x01:c\x92\x41`\n^*\x05Venue25Venue holds details about where the event takes place\xd2\x01\x04name\xd2\x01\x07\x61\x64\x64ress\xd2\x01\x0cianaTimezone\"\x94\x01\n\x1aVenueLimitedFieldsResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t:O\x92\x41L\nJ*\x11Venue (Light ver)25Venue holds details about where the event takes placeBo\n\x1d\x63om.passkit.grpc.EventTicketsZ2stash.passkit.com/io/model/sdk/go/io/event_tickets\xaa\x02\x19PassKit.Grpc.EventTicketsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.event_tickets.venue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.passkit.grpc.EventTicketsZ2stash.passkit.com/io/model/sdk/go/io/event_tickets\252\002\031PassKit.Grpc.EventTickets'
  _VENUE.fields_by_name['id']._options = None
  _VENUE.fields_by_name['id']._serialized_options = b'\222A\002@\001'
  _VENUE.fields_by_name['created']._options = None
  _VENUE.fields_by_name['created']._serialized_options = b'\222A\002@\001'
  _VENUE.fields_by_name['updated']._options = None
  _VENUE.fields_by_name['updated']._serialized_options = b'\222A\002@\001'
  _VENUE._options = None
  _VENUE._serialized_options = b'\222A`\n^*\005Venue25Venue holds details about where the event takes place\322\001\004name\322\001\007address\322\001\014ianaTimezone'
  _VENUELIMITEDFIELDSRESPONSE._options = None
  _VENUELIMITEDFIELDSRESPONSE._serialized_options = b'\222AL\nJ*\021Venue (Light ver)25Venue holds details about where the event takes place'
  _VENUE._serialized_start=186
  _VENUE._serialized_end=606
  _VENUELIMITEDFIELDSRESPONSE._serialized_start=609
  _VENUELIMITEDFIELDSRESPONSE._serialized_end=757
# @@protoc_insertion_point(module_scope)
