# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from passkit_io.common import common_objects_pb2 as io_dot_common_dot_common__objects__pb2
from passkit_io.common import distribution_pb2 as io_dot_common_dot_distribution__pb2
from passkit_io.common import filter_pb2 as io_dot_common_dot_filter__pb2
from passkit_io.common import message_pb2 as io_dot_common_dot_message__pb2
from passkit_io.common import pagination_pb2 as io_dot_common_dot_pagination__pb2
from passkit_io.common import personal_pb2 as io_dot_common_dot_personal__pb2
from passkit_io.member import member_events_pb2 as io_dot_member_dot_member__events__pb2
from passkit_io.member import member_pb2 as io_dot_member_dot_member__pb2
from passkit_io.member import program_pb2 as io_dot_member_dot_program__pb2
from passkit_io.member import tier_pb2 as io_dot_member_dot_tier__pb2


class MembersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createProgram = channel.unary_unary(
                '/members.Members/createProgram',
                request_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateProgram = channel.unary_unary(
                '/members.Members/updateProgram',
                request_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
                response_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                _registered_method=True)
        self.getProgram = channel.unary_unary(
                '/members.Members/getProgram',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                _registered_method=True)
        self.copyProgram = channel.unary_unary(
                '/members.Members/copyProgram',
                request_serializer=io_dot_member_dot_program__pb2.ProgramCopyRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.deleteProgram = channel.unary_unary(
                '/members.Members/deleteProgram',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.listProgramsDeprecated = channel.unary_stream(
                '/members.Members/listProgramsDeprecated',
                request_serializer=io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                _registered_method=True)
        self.listPrograms = channel.unary_stream(
                '/members.Members/listPrograms',
                request_serializer=io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                _registered_method=True)
        self.createTier = channel.unary_unary(
                '/members.Members/createTier',
                request_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateTier = channel.unary_unary(
                '/members.Members/updateTier',
                request_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
                response_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                _registered_method=True)
        self.getTier = channel.unary_unary(
                '/members.Members/getTier',
                request_serializer=io_dot_member_dot_tier__pb2.TierRequestInput.SerializeToString,
                response_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                _registered_method=True)
        self.deleteTier = channel.unary_unary(
                '/members.Members/deleteTier',
                request_serializer=io_dot_member_dot_tier__pb2.TierRequestInput.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.listTiersDeprecated = channel.unary_stream(
                '/members.Members/listTiersDeprecated',
                request_serializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                _registered_method=True)
        self.listTiers = channel.unary_stream(
                '/members.Members/listTiers',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                _registered_method=True)
        self.enrolMember = channel.unary_unary(
                '/members.Members/enrolMember',
                request_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.enrolMemberPublic = channel.unary_unary(
                '/members.Members/enrolMemberPublic',
                request_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.getMemberRecordById = channel.unary_unary(
                '/members.Members/getMemberRecordById',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                _registered_method=True)
        self.getMemberRecordByExternalId = channel.unary_unary(
                '/members.Members/getMemberRecordByExternalId',
                request_serializer=io_dot_member_dot_member__pb2.MemberRecordByExternalIdRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                _registered_method=True)
        self.checkInMember = channel.unary_unary(
                '/members.Members/checkInMember',
                request_serializer=io_dot_member_dot_member__pb2.MemberCheckInOutRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
                _registered_method=True)
        self.checkOutMember = channel.unary_unary(
                '/members.Members/checkOutMember',
                request_serializer=io_dot_member_dot_member__pb2.MemberCheckInOutRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
                _registered_method=True)
        self.listMembersDeprecated = channel.unary_stream(
                '/members.Members/listMembersDeprecated',
                request_serializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                _registered_method=True)
        self.listMembers = channel.unary_stream(
                '/members.Members/listMembers',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                _registered_method=True)
        self.updateMember = channel.unary_unary(
                '/members.Members/updateMember',
                request_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.earnPoints = channel.unary_unary(
                '/members.Members/earnPoints',
                request_serializer=io_dot_member_dot_member__pb2.EarnBurnPointsRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.MemberPoints.FromString,
                _registered_method=True)
        self.burnPoints = channel.unary_unary(
                '/members.Members/burnPoints',
                request_serializer=io_dot_member_dot_member__pb2.EarnBurnPointsRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.MemberPoints.FromString,
                _registered_method=True)
        self.setPoints = channel.unary_unary(
                '/members.Members/setPoints',
                request_serializer=io_dot_member_dot_member__pb2.SetPointsRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__pb2.MemberPoints.FromString,
                _registered_method=True)
        self.changeMemberTier = channel.unary_unary(
                '/members.Members/changeMemberTier',
                request_serializer=io_dot_member_dot_member__pb2.ChangeTierRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
                _registered_method=True)
        self.updateMembersBySegment = channel.unary_unary(
                '/members.Members/updateMembersBySegment',
                request_serializer=io_dot_member_dot_member__pb2.MemberSegmentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.deleteMembersBySegment = channel.unary_unary(
                '/members.Members/deleteMembersBySegment',
                request_serializer=io_dot_member_dot_member__pb2.MemberSegmentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.deleteMember = channel.unary_unary(
                '/members.Members/deleteMember',
                request_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.countMembersDeprecated = channel.unary_unary(
                '/members.Members/countMembersDeprecated',
                request_serializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countMembers = channel.unary_unary(
                '/members.Members/countMembers',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.getMessageHistoryForMember = channel.unary_stream(
                '/members.Members/getMessageHistoryForMember',
                request_serializer=io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=io_dot_common_dot_message__pb2.Message.FromString,
                _registered_method=True)
        self.getMetaKeysForProgram = channel.unary_unary(
                '/members.Members/getMetaKeysForProgram',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Strings.FromString,
                _registered_method=True)
        self.renewMembersExpiry = channel.unary_unary(
                '/members.Members/renewMembersExpiry',
                request_serializer=io_dot_member_dot_member__pb2.UpdateExpiryRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.updateMemberExpiry = channel.unary_unary(
                '/members.Members/updateMemberExpiry',
                request_serializer=io_dot_member_dot_member__pb2.MemberExpiry.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.patchPerson = channel.unary_unary(
                '/members.Members/patchPerson',
                request_serializer=io_dot_common_dot_personal__pb2.PersonRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.countMemberEvents = channel.unary_unary(
                '/members.Members/countMemberEvents',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.listMemberEvents = channel.unary_stream(
                '/members.Members/listMemberEvents',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
                _registered_method=True)
        self.getMemberEventMetaKeysForProgram = channel.unary_unary(
                '/members.Members/getMemberEventMetaKeysForProgram',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Strings.FromString,
                _registered_method=True)
        self.listEventsForMember = channel.unary_stream(
                '/members.Members/listEventsForMember',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
                _registered_method=True)
        self.deleteMemberEvents = channel.unary_unary(
                '/members.Members/deleteMemberEvents',
                request_serializer=io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.deleteEventsForMember = channel.unary_unary(
                '/members.Members/deleteEventsForMember',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.deleteMemberEvent = channel.unary_unary(
                '/members.Members/deleteMemberEvent',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getProgramEnrolment = channel.unary_unary(
                '/members.Members/getProgramEnrolment',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_common_dot_distribution__pb2.EnrolmentUrls.FromString,
                _registered_method=True)


class MembersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createProgram(self, request, context):
        """Create a program record. Allows a user to specify program details around enrolment, renewal and cancellation processes. Optionally allows the user to set the GPS location / Beacons that will trigger a lock-screen alert.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateProgram(self, request, context):
        """Updates an existing program record.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProgram(self, request, context):
        """Gets an existing program record by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def copyProgram(self, request, context):
        """Copies an existing program record to a new record, and allows for status of new program to be set; i.e. copy a draft to published (production) program. Will copy program AND related tier + template records.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteProgram(self, request, context):
        """Deletes an existing program record by id. Deleting a program results in all tiers, and members underneath it being invalidated and removed. Needs to be used with care.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listProgramsDeprecated(self, request, context):
        """Lists all programs for the logged in user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPrograms(self, request, context):
        """Lists all programs for the logged in user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createTier(self, request, context):
        """Create a new tier in an existing member program. Tiers allow a user to categorize their membership program; tiers allow for additional detail that is specific to that 'group' of members. A program needs at least one tier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTier(self, request, context):
        """Updates a tier by tier id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTier(self, request, context):
        """Gets a tier by tier ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTier(self, request, context):
        """Deletes a tier. Deleting a tier will invalidate and delete all the passes that are in the tier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTiersDeprecated(self, request, context):
        """Lists all the tiers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTiers(self, request, context):
        """Lists all the tiers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def enrolMember(self, request, context):
        """Enrols a new member into a tier of a program. Returns the PassKit Member ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def enrolMemberPublic(self, request, context):
        """Enrols a new member into the default tier (lowest tier index) of a program. Returns the PassKit Member ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMemberRecordById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMemberRecordByExternalId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkInMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkOutMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listMembersDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def earnPoints(self, request, context):
        """@todo: define callback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def burnPoints(self, request, context):
        """@todo: define callback
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changeMemberTier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateMembersBySegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMembersBySegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countMembersDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessageHistoryForMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetaKeysForProgram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def renewMembersExpiry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateMemberExpiry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def patchPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countMemberEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listMemberEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMemberEventMetaKeysForProgram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listEventsForMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMemberEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteEventsForMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMemberEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProgramEnrolment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MembersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.createProgram,
                    request_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.updateProgram,
                    request_deserializer=io_dot_member_dot_program__pb2.Program.FromString,
                    response_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
            ),
            'getProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.getProgram,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
            ),
            'copyProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.copyProgram,
                    request_deserializer=io_dot_member_dot_program__pb2.ProgramCopyRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'deleteProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteProgram,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'listProgramsDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listProgramsDeprecated,
                    request_deserializer=io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
            ),
            'listPrograms': grpc.unary_stream_rpc_method_handler(
                    servicer.listPrograms,
                    request_deserializer=io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=io_dot_member_dot_program__pb2.Program.SerializeToString,
            ),
            'createTier': grpc.unary_unary_rpc_method_handler(
                    servicer.createTier,
                    request_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateTier': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTier,
                    request_deserializer=io_dot_member_dot_tier__pb2.Tier.FromString,
                    response_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            ),
            'getTier': grpc.unary_unary_rpc_method_handler(
                    servicer.getTier,
                    request_deserializer=io_dot_member_dot_tier__pb2.TierRequestInput.FromString,
                    response_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            ),
            'deleteTier': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTier,
                    request_deserializer=io_dot_member_dot_tier__pb2.TierRequestInput.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'listTiersDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listTiersDeprecated,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.FromString,
                    response_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            ),
            'listTiers': grpc.unary_stream_rpc_method_handler(
                    servicer.listTiers,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            ),
            'enrolMember': grpc.unary_unary_rpc_method_handler(
                    servicer.enrolMember,
                    request_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'enrolMemberPublic': grpc.unary_unary_rpc_method_handler(
                    servicer.enrolMemberPublic,
                    request_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'getMemberRecordById': grpc.unary_unary_rpc_method_handler(
                    servicer.getMemberRecordById,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
            ),
            'getMemberRecordByExternalId': grpc.unary_unary_rpc_method_handler(
                    servicer.getMemberRecordByExternalId,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberRecordByExternalIdRequest.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
            ),
            'checkInMember': grpc.unary_unary_rpc_method_handler(
                    servicer.checkInMember,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberCheckInOutRequest.FromString,
                    response_serializer=io_dot_member_dot_member__events__pb2.MemberEvent.SerializeToString,
            ),
            'checkOutMember': grpc.unary_unary_rpc_method_handler(
                    servicer.checkOutMember,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberCheckInOutRequest.FromString,
                    response_serializer=io_dot_member_dot_member__events__pb2.MemberEvent.SerializeToString,
            ),
            'listMembersDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listMembersDeprecated,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
            ),
            'listMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.listMembers,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.Member.SerializeToString,
            ),
            'updateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.updateMember,
                    request_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'earnPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.earnPoints,
                    request_deserializer=io_dot_member_dot_member__pb2.EarnBurnPointsRequest.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.MemberPoints.SerializeToString,
            ),
            'burnPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.burnPoints,
                    request_deserializer=io_dot_member_dot_member__pb2.EarnBurnPointsRequest.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.MemberPoints.SerializeToString,
            ),
            'setPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.setPoints,
                    request_deserializer=io_dot_member_dot_member__pb2.SetPointsRequest.FromString,
                    response_serializer=io_dot_member_dot_member__pb2.MemberPoints.SerializeToString,
            ),
            'changeMemberTier': grpc.unary_unary_rpc_method_handler(
                    servicer.changeMemberTier,
                    request_deserializer=io_dot_member_dot_member__pb2.ChangeTierRequest.FromString,
                    response_serializer=io_dot_member_dot_member__events__pb2.MemberEvent.SerializeToString,
            ),
            'updateMembersBySegment': grpc.unary_unary_rpc_method_handler(
                    servicer.updateMembersBySegment,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberSegmentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'deleteMembersBySegment': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMembersBySegment,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberSegmentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'deleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMember,
                    request_deserializer=io_dot_member_dot_member__pb2.Member.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'countMembersDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.countMembersDeprecated,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequestDeprecated.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.countMembers,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'getMessageHistoryForMember': grpc.unary_stream_rpc_method_handler(
                    servicer.getMessageHistoryForMember,
                    request_deserializer=io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=io_dot_common_dot_message__pb2.Message.SerializeToString,
            ),
            'getMetaKeysForProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.getMetaKeysForProgram,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Strings.SerializeToString,
            ),
            'renewMembersExpiry': grpc.unary_unary_rpc_method_handler(
                    servicer.renewMembersExpiry,
                    request_deserializer=io_dot_member_dot_member__pb2.UpdateExpiryRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'updateMemberExpiry': grpc.unary_unary_rpc_method_handler(
                    servicer.updateMemberExpiry,
                    request_deserializer=io_dot_member_dot_member__pb2.MemberExpiry.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'patchPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.patchPerson,
                    request_deserializer=io_dot_common_dot_personal__pb2.PersonRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'countMemberEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.countMemberEvents,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'listMemberEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.listMemberEvents,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=io_dot_member_dot_member__events__pb2.MemberEvent.SerializeToString,
            ),
            'getMemberEventMetaKeysForProgram': grpc.unary_unary_rpc_method_handler(
                    servicer.getMemberEventMetaKeysForProgram,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Strings.SerializeToString,
            ),
            'listEventsForMember': grpc.unary_stream_rpc_method_handler(
                    servicer.listEventsForMember,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_member_dot_member__events__pb2.MemberEvent.SerializeToString,
            ),
            'deleteMemberEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMemberEvents,
                    request_deserializer=io_dot_member_dot_member__pb2.ListRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'deleteEventsForMember': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteEventsForMember,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'deleteMemberEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMemberEvent,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getProgramEnrolment': grpc.unary_unary_rpc_method_handler(
                    servicer.getProgramEnrolment,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_common_dot_distribution__pb2.EnrolmentUrls.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'members.Members', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('members.Members', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Members(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/createProgram',
            io_dot_member_dot_program__pb2.Program.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/updateProgram',
            io_dot_member_dot_program__pb2.Program.SerializeToString,
            io_dot_member_dot_program__pb2.Program.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getProgram',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_member_dot_program__pb2.Program.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def copyProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/copyProgram',
            io_dot_member_dot_program__pb2.ProgramCopyRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteProgram',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listProgramsDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listProgramsDeprecated',
            io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            io_dot_member_dot_program__pb2.Program.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listPrograms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listPrograms',
            io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            io_dot_member_dot_program__pb2.Program.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/createTier',
            io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/updateTier',
            io_dot_member_dot_tier__pb2.Tier.SerializeToString,
            io_dot_member_dot_tier__pb2.Tier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getTier',
            io_dot_member_dot_tier__pb2.TierRequestInput.SerializeToString,
            io_dot_member_dot_tier__pb2.Tier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteTier',
            io_dot_member_dot_tier__pb2.TierRequestInput.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listTiersDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listTiersDeprecated',
            io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
            io_dot_member_dot_tier__pb2.Tier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listTiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listTiers',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            io_dot_member_dot_tier__pb2.Tier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def enrolMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/enrolMember',
            io_dot_member_dot_member__pb2.Member.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def enrolMemberPublic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/enrolMemberPublic',
            io_dot_member_dot_member__pb2.Member.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMemberRecordById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getMemberRecordById',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_member_dot_member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMemberRecordByExternalId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getMemberRecordByExternalId',
            io_dot_member_dot_member__pb2.MemberRecordByExternalIdRequest.SerializeToString,
            io_dot_member_dot_member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def checkInMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/checkInMember',
            io_dot_member_dot_member__pb2.MemberCheckInOutRequest.SerializeToString,
            io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def checkOutMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/checkOutMember',
            io_dot_member_dot_member__pb2.MemberCheckInOutRequest.SerializeToString,
            io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listMembersDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listMembersDeprecated',
            io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
            io_dot_member_dot_member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listMembers',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            io_dot_member_dot_member__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/updateMember',
            io_dot_member_dot_member__pb2.Member.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def earnPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/earnPoints',
            io_dot_member_dot_member__pb2.EarnBurnPointsRequest.SerializeToString,
            io_dot_member_dot_member__pb2.MemberPoints.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def burnPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/burnPoints',
            io_dot_member_dot_member__pb2.EarnBurnPointsRequest.SerializeToString,
            io_dot_member_dot_member__pb2.MemberPoints.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/setPoints',
            io_dot_member_dot_member__pb2.SetPointsRequest.SerializeToString,
            io_dot_member_dot_member__pb2.MemberPoints.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def changeMemberTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/changeMemberTier',
            io_dot_member_dot_member__pb2.ChangeTierRequest.SerializeToString,
            io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateMembersBySegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/updateMembersBySegment',
            io_dot_member_dot_member__pb2.MemberSegmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteMembersBySegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteMembersBySegment',
            io_dot_member_dot_member__pb2.MemberSegmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteMember',
            io_dot_member_dot_member__pb2.Member.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countMembersDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/countMembersDeprecated',
            io_dot_member_dot_member__pb2.ListRequestDeprecated.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/countMembers',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMessageHistoryForMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/getMessageHistoryForMember',
            io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            io_dot_common_dot_message__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMetaKeysForProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getMetaKeysForProgram',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Strings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def renewMembersExpiry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/renewMembersExpiry',
            io_dot_member_dot_member__pb2.UpdateExpiryRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateMemberExpiry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/updateMemberExpiry',
            io_dot_member_dot_member__pb2.MemberExpiry.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def patchPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/patchPerson',
            io_dot_common_dot_personal__pb2.PersonRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countMemberEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/countMemberEvents',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listMemberEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listMemberEvents',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMemberEventMetaKeysForProgram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getMemberEventMetaKeysForProgram',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Strings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listEventsForMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/members.Members/listEventsForMember',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_member_dot_member__events__pb2.MemberEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteMemberEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteMemberEvents',
            io_dot_member_dot_member__pb2.ListRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteEventsForMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteEventsForMember',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteMemberEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/deleteMemberEvent',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getProgramEnrolment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/members.Members/getProgramEnrolment',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_common_dot_distribution__pb2.EnrolmentUrls.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
