# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/core/a_rpc_messages.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'io/core/a_rpc_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from passkit_io.common import common_objects_pb2 as io_dot_common_dot_common__objects__pb2
from passkit_io.common import message_pb2 as io_dot_common_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/core/a_rpc_messages.proto\x12\x02io\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1eio/common/common_objects.proto\x1a\x17io/common/message.proto2\xd8\x06\n\x08Messages\x12o\n\ngetMessage\x12\x06.io.Id\x1a\x0b.io.Message\"L\x92\x41\x34\x12\x0bGet message\x1a%Gets an single message by message id.\x82\xd3\xe4\x93\x02\x0f\x12\r/message/{id}\x12\x96\x01\n\rcreateMessage\x12\x0b.io.Message\x1a\x06.io.Id\"p\x92\x41Z\x12\x0e\x43reate Message\x1a\x16\x43reates a new message.J0\n\x03\x34\x30\x30\x12)\n\'There is a problem with the input data.\x82\xd3\xe4\x93\x02\r\"\x08/message:\x01*\x12\xa4\x01\n\rupdateMessage\x12\x0b.io.Message\x1a\x16.google.protobuf.Empty\"n\x92\x41S\x12\x0eUpdate Message\x1a\x0fUpdate message.J0\n\x03\x34\x30\x30\x12)\n\'There is a problem with the input data.\x82\xd3\xe4\x93\x02\x12\x1a\r/message/{id}:\x01*\x12\xb4\x01\n\rdeleteMessage\x12\x06.io.Id\x1a\x16.google.protobuf.Empty\"\x82\x01\x92\x41j\x12\x0e\x44\x65lete Message\x1a\x32\x44\x65leting a message will remove it from all passes.J$\n\x03\x34\x30\x34\x12\x1d\n\x1bMessage could not be found.\x82\xd3\xe4\x93\x02\x0f*\r/message/{id}\x12\xe3\x01\n\x0bsendMessage\x12\x16.io.SendMessageRequest\x1a\x17.io.SendMessageResponse\"\xa2\x01\x92\x41\x86\x01\x12\x0cSend Message\x1a\x44Sends a message to an array of passIds, or to every pass in a class.J0\n\x03\x34\x30\x30\x12)\n\'There is a problem with the input data.\x82\xd3\xe4\x93\x02\x12\"\r/message/send:\x01*BG\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.core.a_rpc_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _globals['_MESSAGES'].methods_by_name['getMessage']._loaded_options = None
  _globals['_MESSAGES'].methods_by_name['getMessage']._serialized_options = b'\222A4\022\013Get message\032%Gets an single message by message id.\202\323\344\223\002\017\022\r/message/{id}'
  _globals['_MESSAGES'].methods_by_name['createMessage']._loaded_options = None
  _globals['_MESSAGES'].methods_by_name['createMessage']._serialized_options = b'\222AZ\022\016Create Message\032\026Creates a new message.J0\n\003400\022)\n\'There is a problem with the input data.\202\323\344\223\002\r\"\010/message:\001*'
  _globals['_MESSAGES'].methods_by_name['updateMessage']._loaded_options = None
  _globals['_MESSAGES'].methods_by_name['updateMessage']._serialized_options = b'\222AS\022\016Update Message\032\017Update message.J0\n\003400\022)\n\'There is a problem with the input data.\202\323\344\223\002\022\032\r/message/{id}:\001*'
  _globals['_MESSAGES'].methods_by_name['deleteMessage']._loaded_options = None
  _globals['_MESSAGES'].methods_by_name['deleteMessage']._serialized_options = b'\222Aj\022\016Delete Message\0322Deleting a message will remove it from all passes.J$\n\003404\022\035\n\033Message could not be found.\202\323\344\223\002\017*\r/message/{id}'
  _globals['_MESSAGES'].methods_by_name['sendMessage']._loaded_options = None
  _globals['_MESSAGES'].methods_by_name['sendMessage']._serialized_options = b'\222A\206\001\022\014Send Message\032DSends a message to an array of passIds, or to every pass in a class.J0\n\003400\022)\n\'There is a problem with the input data.\202\323\344\223\002\022\"\r/message/send:\001*'
  _globals['_MESSAGES']._serialized_start=201
  _globals['_MESSAGES']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
