# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from passkit.io.certificate import certificate_pb2 as passkit_dot_io_dot_certificate_dot_certificate__pb2
from passkit.io.common import common_objects_pb2 as passkit_dot_io_dot_common_dot_common__objects__pb2
from passkit.io.common import filter_pb2 as passkit_dot_io_dot_common_dot_filter__pb2
from passkit.io.common import pagination_pb2 as passkit_dot_io_dot_common_dot_pagination__pb2


class CertificatesStub(object):
    """Manage your Apple Wallet Pass Type Identifiers & Certificates
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAppleCertificateData = channel.unary_unary(
                '/io.Certificates/getAppleCertificateData',
                request_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.PassTypeIdentifier.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
                _registered_method=True)
        self.getCertificateSigningRequest = channel.unary_unary(
                '/io.Certificates/getCertificateSigningRequest',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateSigningRequest.FromString,
                _registered_method=True)
        self.addAppleCertificate = channel.unary_unary(
                '/io.Certificates/addAppleCertificate',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
                _registered_method=True)
        self.updateAppleCertificate = channel.unary_unary(
                '/io.Certificates/updateAppleCertificate',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
                _registered_method=True)
        self.listAppleCertificatesDeprecated = channel.unary_stream(
                '/io.Certificates/listAppleCertificatesDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
                _registered_method=True)
        self.listAppleCertificates = channel.unary_stream(
                '/io.Certificates/listAppleCertificates',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
                _registered_method=True)
        self.countAppleCertificatesDeprecated = channel.unary_unary(
                '/io.Certificates/countAppleCertificatesDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countAppleCertificates = channel.unary_unary(
                '/io.Certificates/countAppleCertificates',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.sendNFCSigningCredentials = channel.unary_unary(
                '/io.Certificates/sendNFCSigningCredentials',
                request_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.NFCSigningCredentialsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CertificatesServicer(object):
    """Manage your Apple Wallet Pass Type Identifiers & Certificates
    """

    def getAppleCertificateData(self, request, context):
        """Retrieves the Apple pass certificate data for the provided Pass Type Identifier. Required Fields: passTypeId.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCertificateSigningRequest(self, request, context):
        """Retrieves a Certificate Signing Request (CSR) for the logged-in user. This is used to generate a new certificate on the Apple Developer portal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addAppleCertificate(self, request, context):
        """Uploads a new Apple certificate for use with Wallet passes. Required Field: fileBytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateAppleCertificate(self, request, context):
        """Updates or renews an existing Apple certificate by uploading a new one. Required Fields: fileBytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listAppleCertificatesDeprecated(self, request, context):
        """[DEPRECATED] Returns a paginated list of Apple pass certificates for the current user. Required Fields: pagination fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listAppleCertificates(self, request, context):
        """Returns a filtered list of Apple pass certificates for the current user. Required Fields: Filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countAppleCertificatesDeprecated(self, request, context):
        """[DEPRECATED] Returns the count of Apple certificates for the current user based on pagination criteria. Required fields: pagination fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countAppleCertificates(self, request, context):
        """Returns the count of Apple certificates for the current user using filter criteria. Required Fields: Filters (can be empty, but must be present)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendNFCSigningCredentials(self, request, context):
        """Sends NFC signing credentials for an NFC-enabled Apple certificate to the user's registered email address. Required Fields: certificateId, user email must be associated with the cert.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CertificatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAppleCertificateData': grpc.unary_unary_rpc_method_handler(
                    servicer.getAppleCertificateData,
                    request_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.PassTypeIdentifier.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.SerializeToString,
            ),
            'getCertificateSigningRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.getCertificateSigningRequest,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateSigningRequest.SerializeToString,
            ),
            'addAppleCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.addAppleCertificate,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.SerializeToString,
            ),
            'updateAppleCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.updateAppleCertificate,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.SerializeToString,
            ),
            'listAppleCertificatesDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listAppleCertificatesDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.SerializeToString,
            ),
            'listAppleCertificates': grpc.unary_stream_rpc_method_handler(
                    servicer.listAppleCertificates,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.SerializeToString,
            ),
            'countAppleCertificatesDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.countAppleCertificatesDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countAppleCertificates': grpc.unary_unary_rpc_method_handler(
                    servicer.countAppleCertificates,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'sendNFCSigningCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.sendNFCSigningCredentials,
                    request_deserializer=passkit_dot_io_dot_certificate_dot_certificate__pb2.NFCSigningCredentialsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.Certificates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('io.Certificates', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Certificates(object):
    """Manage your Apple Wallet Pass Type Identifiers & Certificates
    """

    @staticmethod
    def getAppleCertificateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/getAppleCertificateData',
            passkit_dot_io_dot_certificate_dot_certificate__pb2.PassTypeIdentifier.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCertificateSigningRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/getCertificateSigningRequest',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateSigningRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addAppleCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/addAppleCertificate',
            passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateAppleCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/updateAppleCertificate',
            passkit_dot_io_dot_common_dot_common__objects__pb2.FileBytes.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listAppleCertificatesDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Certificates/listAppleCertificatesDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listAppleCertificates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Certificates/listAppleCertificates',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_certificate_dot_certificate__pb2.CertificateData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countAppleCertificatesDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/countAppleCertificatesDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countAppleCertificates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/countAppleCertificates',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendNFCSigningCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Certificates/sendNFCSigningCredentials',
            passkit_dot_io_dot_certificate_dot_certificate__pb2.NFCSigningCredentialsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
