# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from passkit.ct.scheduler import scheduler_pb2 as passkit_dot_ct_dot_scheduler_dot_scheduler__pb2
from passkit.io.common import common_objects_pb2 as passkit_dot_io_dot_common_dot_common__objects__pb2
from passkit.io.scheduler import scheduler_pb2 as passkit_dot_io_dot_scheduler_dot_scheduler__pb2


class SchedulerStub(object):
    """The PassKit Scheduler API allows you to automate tasks within your PassKit programs. This API allows you to schedule one-time or recurring jobs that interact with other PassKit APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createSchedulingJob = channel.unary_unary(
                '/scheduler.Scheduler/createSchedulingJob',
                request_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
                _registered_method=True)
        self.getSchedulingJob = channel.unary_unary(
                '/scheduler.Scheduler/getSchedulingJob',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.FromString,
                _registered_method=True)
        self.updateSchedulingJob = channel.unary_unary(
                '/scheduler.Scheduler/updateSchedulingJob',
                request_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
                _registered_method=True)
        self.patchSchedulingJob = channel.unary_unary(
                '/scheduler.Scheduler/patchSchedulingJob',
                request_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
                _registered_method=True)
        self.deleteSchedulingJob = channel.unary_unary(
                '/scheduler.Scheduler/deleteSchedulingJob',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getSchedulingJobHistory = channel.unary_unary(
                '/scheduler.Scheduler/getSchedulingJobHistory',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.FromString,
                _registered_method=True)
        self.listSchedulingJobHistories = channel.unary_stream(
                '/scheduler.Scheduler/listSchedulingJobHistories',
                request_serializer=passkit_dot_io_dot_scheduler_dot_scheduler__pb2.ListRequest.SerializeToString,
                response_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.FromString,
                _registered_method=True)


class SchedulerServicer(object):
    """The PassKit Scheduler API allows you to automate tasks within your PassKit programs. This API allows you to schedule one-time or recurring jobs that interact with other PassKit APIs.
    """

    def createSchedulingJob(self, request, context):
        """Creates a scheduling job. Required Fields: scheduleType, protocol, classId, jobName, scheduledTime, timezone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSchedulingJob(self, request, context):
        """Retrieves a scheduling job by its ID. If the job has been deleted, only history logs will be returned. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateSchedulingJob(self, request, context):
        """Updates an existing scheduling job. The full SchedulingJob object must be supplied. Empty/null fields will overwrite existing data. Required Fields: id, scheduleType, protocol, classId, jobName, scheduledTime, timezone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def patchSchedulingJob(self, request, context):
        """Patch updates a scheduling job. Only supplied fields will be updated. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteSchedulingJob(self, request, context):
        """Deletes a scheduling job by ID. History logs remain available after deletion. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSchedulingJobHistory(self, request, context):
        """Retrieves a specific scheduling job history log by ID. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listSchedulingJobHistories(self, request, context):
        """Lists all history logs for a given scheduling job. Required Fields: jobId.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createSchedulingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.createSchedulingJob,
                    request_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.SerializeToString,
            ),
            'getSchedulingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.getSchedulingJob,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
            ),
            'updateSchedulingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.updateSchedulingJob,
                    request_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.SerializeToString,
            ),
            'patchSchedulingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.patchSchedulingJob,
                    request_deserializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.SerializeToString,
            ),
            'deleteSchedulingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteSchedulingJob,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getSchedulingJobHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.getSchedulingJobHistory,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.SerializeToString,
            ),
            'listSchedulingJobHistories': grpc.unary_stream_rpc_method_handler(
                    servicer.listSchedulingJobHistories,
                    request_deserializer=passkit_dot_io_dot_scheduler_dot_scheduler__pb2.ListRequest.FromString,
                    response_serializer=passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """The PassKit Scheduler API allows you to automate tasks within your PassKit programs. This API allows you to schedule one-time or recurring jobs that interact with other PassKit APIs.
    """

    @staticmethod
    def createSchedulingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/createSchedulingJob',
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSchedulingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/getSchedulingJob',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateSchedulingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/updateSchedulingJob',
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def patchSchedulingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/patchSchedulingJob',
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJob.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.SchedulingJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteSchedulingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/deleteSchedulingJob',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSchedulingJobHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Scheduler/getSchedulingJobHistory',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listSchedulingJobHistories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scheduler.Scheduler/listSchedulingJobHistories',
            passkit_dot_io_dot_scheduler_dot_scheduler__pb2.ListRequest.SerializeToString,
            passkit_dot_ct_dot_scheduler_dot_scheduler__pb2.JobHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
