# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/scheduler/scheduler.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'io/scheduler/scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passkit_io.common import filter_pb2 as io_dot_common_dot_filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/scheduler/scheduler.proto\x12\tscheduler\x1a\x16io/common/filter.proto\":\n\x0bListRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x1c\n\x07\x66ilters\x18\x02 \x01(\x0b\x32\x0b.io.FiltersBe\n\x1a\x63om.passkit.grpc.SchedulerZ.stash.passkit.com/io/model/sdk/go/io/scheduler\xaa\x02\x16PassKit.Grpc.Schedulerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.scheduler.scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.passkit.grpc.SchedulerZ.stash.passkit.com/io/model/sdk/go/io/scheduler\252\002\026PassKit.Grpc.Scheduler'
  _globals['_LISTREQUEST']._serialized_start=67
  _globals['_LISTREQUEST']._serialized_end=125
# @@protoc_insertion_point(module_scope)
