# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from passkit.io.common import common_objects_pb2 as passkit_dot_io_dot_common_dot_common__objects__pb2
from passkit.io.common import filter_pb2 as passkit_dot_io_dot_common_dot_filter__pb2
from passkit.io.common import pagination_pb2 as passkit_dot_io_dot_common_dot_pagination__pb2
from passkit.io.image import image_pb2 as passkit_dot_io_dot_image_dot_image__pb2


class ImagesStub(object):
    """The PassKit Images API lets you manage your image assets for Apple Wallet, Google Wallet and the data collection pages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setProfileImage = channel.unary_unary(
                '/io.Images/setProfileImage',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.ProfileImageInput.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getProfileImage = channel.unary_unary(
                '/io.Images/getProfileImage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
                _registered_method=True)
        self.createImages = channel.unary_unary(
                '/io.Images/createImages',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.CreateImageInput.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageIds.FromString,
                _registered_method=True)
        self.updateImage = channel.unary_unary(
                '/io.Images/updateImage',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.UpdateImageInput.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.getImageURL = channel.unary_unary(
                '/io.Images/getImageURL',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
                _registered_method=True)
        self.getStampImageURL = channel.unary_unary(
                '/io.Images/getStampImageURL',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageRequest.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
                _registered_method=True)
        self.getStampImageConfig = channel.unary_unary(
                '/io.Images/getStampImageConfig',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.FromString,
                _registered_method=True)
        self.updateStampImageConfig = channel.unary_unary(
                '/io.Images/updateStampImageConfig',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.getStampImagePreview = channel.unary_unary(
                '/io.Images/getStampImagePreview',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.StampImagePreviewRequest.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.StampImagePreview.FromString,
                _registered_method=True)
        self.getLocalizedImageURL = channel.unary_unary(
                '/io.Images/getLocalizedImageURL',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
                _registered_method=True)
        self.getProfileImageById = channel.unary_unary(
                '/io.Images/getProfileImageById',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
                _registered_method=True)
        self.getImageBundle = channel.unary_unary(
                '/io.Images/getImageBundle',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageBundle.FromString,
                _registered_method=True)
        self.getImageData = channel.unary_unary(
                '/io.Images/getImageData',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.deleteImage = channel.unary_unary(
                '/io.Images/deleteImage',
                request_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.deleteLocalizedImage = channel.unary_unary(
                '/io.Images/deleteLocalizedImage',
                request_serializer=passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.listImagesForUserDeprecated = channel.unary_stream(
                '/io.Images/listImagesForUserDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.listImagesForUser = channel.unary_stream(
                '/io.Images/listImagesForUser',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.listImagesDeprecated = channel.unary_stream(
                '/io.Images/listImagesDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.listImages = channel.unary_stream(
                '/io.Images/listImages',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
                _registered_method=True)
        self.countImagesDeprecated = channel.unary_unary(
                '/io.Images/countImagesDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countImages = channel.unary_unary(
                '/io.Images/countImages',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countImagesForUserDeprecated = channel.unary_unary(
                '/io.Images/countImagesForUserDeprecated',
                request_serializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countImagesForUser = channel.unary_unary(
                '/io.Images/countImagesForUser',
                request_serializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)


class ImagesServicer(object):
    """The PassKit Images API lets you manage your image assets for Apple Wallet, Google Wallet and the data collection pages.
    """

    def setProfileImage(self, request, context):
        """Set the profile image for the logged in user. Required Fields: imageData.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProfileImage(self, request, context):
        """Get the profile image URL for the logged in user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createImages(self, request, context):
        """Creates one or more images. Image data is provided in base64. Required Fields: name, imageData.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateImage(self, request, context):
        """Updates an image record's metadata. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageURL(self, request, context):
        """Retrieves an image URL by its ID. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStampImageURL(self, request, context):
        """Retrieves a stamp image URL with the supplied stamp status. Required Fields: id and status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStampImageConfig(self, request, context):
        """Retrieves the configuration of a stamp image. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateStampImageConfig(self, request, context):
        """Updates a stamp image configuration. Required Fields: id and config fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStampImagePreview(self, request, context):
        """Gets a preview image of the provided stamp image configuration. Required Fields: stampImageConfig and status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLocalizedImageURL(self, request, context):
        """Retrieves a localized image URL for a specific language. Required Fields: iD and languageCode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProfileImageById(self, request, context):
        """Retrieves a profile image URL by a specific ID. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageBundle(self, request, context):
        """Retrieves an image bundle (ZIP) containing all images for the given ID. Required Fields: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageData(self, request, context):
        """Retrieves metadata for an image record. Required: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteImage(self, request, context):
        """Deletes an image record. Required: id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteLocalizedImage(self, request, context):
        """Deletes a localized version of an image. Required Fields: id and language code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listImagesForUserDeprecated(self, request, context):
        """[DEPRECATED] Retrieves all user-owned images using pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listImagesForUser(self, request, context):
        """Retrieves all images stored under the user account using filters. Required Fields: filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listImagesDeprecated(self, request, context):
        """[DEPRECATED] Retrieves all images available to the company.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listImages(self, request, context):
        """Retrieves all images stored under the company using filters. Required Fields: filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countImagesDeprecated(self, request, context):
        """[DEPRECATED] Returns the count of all images available to the user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countImages(self, request, context):
        """Returns the count of all images available to the user using filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countImagesForUserDeprecated(self, request, context):
        """[DEPRECATED] Returns the count of images stored under the user's account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countImagesForUser(self, request, context):
        """Returns the count of images stored under the user's account using filters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setProfileImage': grpc.unary_unary_rpc_method_handler(
                    servicer.setProfileImage,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.ProfileImageInput.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getProfileImage': grpc.unary_unary_rpc_method_handler(
                    servicer.getProfileImage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.SerializeToString,
            ),
            'createImages': grpc.unary_unary_rpc_method_handler(
                    servicer.createImages,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.CreateImageInput.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageIds.SerializeToString,
            ),
            'updateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.updateImage,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.UpdateImageInput.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'getImageURL': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageURL,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.SerializeToString,
            ),
            'getStampImageURL': grpc.unary_unary_rpc_method_handler(
                    servicer.getStampImageURL,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageRequest.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.SerializeToString,
            ),
            'getStampImageConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.getStampImageConfig,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.SerializeToString,
            ),
            'updateStampImageConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.updateStampImageConfig,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'getStampImagePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.getStampImagePreview,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.StampImagePreviewRequest.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.StampImagePreview.SerializeToString,
            ),
            'getLocalizedImageURL': grpc.unary_unary_rpc_method_handler(
                    servicer.getLocalizedImageURL,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.SerializeToString,
            ),
            'getProfileImageById': grpc.unary_unary_rpc_method_handler(
                    servicer.getProfileImageById,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Url.SerializeToString,
            ),
            'getImageBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageBundle,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageBundle.SerializeToString,
            ),
            'getImageData': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageData,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'deleteImage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteImage,
                    request_deserializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'deleteLocalizedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteLocalizedImage,
                    request_deserializer=passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'listImagesForUserDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listImagesForUserDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'listImagesForUser': grpc.unary_stream_rpc_method_handler(
                    servicer.listImagesForUser,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'listImagesDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listImagesDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'listImages': grpc.unary_stream_rpc_method_handler(
                    servicer.listImages,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.SerializeToString,
            ),
            'countImagesDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.countImagesDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countImages': grpc.unary_unary_rpc_method_handler(
                    servicer.countImages,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countImagesForUserDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.countImagesForUserDeprecated,
                    request_deserializer=passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countImagesForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.countImagesForUser,
                    request_deserializer=passkit_dot_io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=passkit_dot_io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'io.Images', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('io.Images', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Images(object):
    """The PassKit Images API lets you manage your image assets for Apple Wallet, Google Wallet and the data collection pages.
    """

    @staticmethod
    def setProfileImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/setProfileImage',
            passkit_dot_io_dot_image_dot_image__pb2.ProfileImageInput.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getProfileImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getProfileImage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/createImages',
            passkit_dot_io_dot_image_dot_image__pb2.CreateImageInput.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageIds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/updateImage',
            passkit_dot_io_dot_image_dot_image__pb2.UpdateImageInput.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getImageURL',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStampImageURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getStampImageURL',
            passkit_dot_io_dot_image_dot_image__pb2.StampImageRequest.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStampImageConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getStampImageConfig',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateStampImageConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/updateStampImageConfig',
            passkit_dot_io_dot_image_dot_image__pb2.StampImageConfig.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStampImagePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getStampImagePreview',
            passkit_dot_io_dot_image_dot_image__pb2.StampImagePreviewRequest.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.StampImagePreview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getLocalizedImageURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getLocalizedImageURL',
            passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getProfileImageById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getProfileImageById',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Url.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getImageBundle',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/getImageData',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/deleteImage',
            passkit_dot_io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteLocalizedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/deleteLocalizedImage',
            passkit_dot_io_dot_image_dot_image__pb2.LocalizedImageInput.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listImagesForUserDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Images/listImagesForUserDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listImagesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Images/listImagesForUser',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listImagesDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Images/listImagesDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/io.Images/listImages',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_image_dot_image__pb2.ImageRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countImagesDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/countImagesDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/countImages',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countImagesForUserDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/countImagesForUserDeprecated',
            passkit_dot_io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countImagesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/io.Images/countImagesForUser',
            passkit_dot_io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            passkit_dot_io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
