# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passkit/io/common/batch_update.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passkit/io/common/batch_update.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passkit.io.common import filter_pb2 as passkit_dot_io_dot_common_dot_filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$passkit/io/common/batch_update.proto\x12\x02io\x1a\x1epasskit/io/common/filter.proto\"}\n\x11\x42\x61tchUpdateMember\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63Id\x18\x02 \x01(\r\x12\x12\n\nprotocolId\x18\x03 \x01(\t\x12\x12\n\nmemberUUID\x18\x04 \x01(\t\x12\'\n\x07request\x18\x05 \x01(\x0b\x32\x16.io.BatchUpdateRequest\"t\n\x12\x42\x61tchUpdateRequest\x12\x0f\n\x07\x63lassId\x18\x01 \x01(\t\x12%\n\x0c\x66ilterGroups\x18\x02 \x03(\x0b\x32\x0f.io.FilterGroup\x12&\n\rupdateEntries\x18\x03 \x03(\x0b\x32\x0f.io.UpdateEntry\"T\n\x0bUpdateEntry\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\'\n\nupdateType\x18\x03 \x01(\x0e\x32\x13.io.BatchUpdateType*S\n\x0f\x42\x61tchUpdateType\x12\x1b\n\x17\x42\x41TCH_UPDATE_DO_NOT_USE\x10\x00\x12\x07\n\x03SET\x10\x01\x12\x0c\n\x08INCREASE\x10\x02\x12\x0c\n\x08\x44\x45\x43REASE\x10\x03\x42G\n\x10\x63om.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\xaa\x02\x0cPassKit.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passkit.io.common.batch_update_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.passkit.grpcZ$stash.passkit.com/io/model/sdk/go/io\252\002\014PassKit.Grpc'
  _globals['_BATCHUPDATETYPE']._serialized_start=407
  _globals['_BATCHUPDATETYPE']._serialized_end=490
  _globals['_BATCHUPDATEMEMBER']._serialized_start=76
  _globals['_BATCHUPDATEMEMBER']._serialized_end=201
  _globals['_BATCHUPDATEREQUEST']._serialized_start=203
  _globals['_BATCHUPDATEREQUEST']._serialized_end=319
  _globals['_UPDATEENTRY']._serialized_start=321
  _globals['_UPDATEENTRY']._serialized_end=405
# @@protoc_insertion_point(module_scope)
