# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from passkit_io.common import common_objects_pb2 as io_dot_common_dot_common__objects__pb2
from passkit_io.common import filter_pb2 as io_dot_common_dot_filter__pb2
from passkit_io.common import pagination_pb2 as io_dot_common_dot_pagination__pb2
from passkit_io.common import personal_pb2 as io_dot_common_dot_personal__pb2
from passkit_io.common import reporting_pb2 as io_dot_common_dot_reporting__pb2
from passkit_io.single_use_coupons import campaign_pb2 as io_dot_single__use__coupons_dot_campaign__pb2
from passkit_io.single_use_coupons import coupon_pb2 as io_dot_single__use__coupons_dot_coupon__pb2
from passkit_io.single_use_coupons import offer_pb2 as io_dot_single__use__coupons_dot_offer__pb2


class SingleUseCouponsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/createCouponCampaign',
                request_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/updateCouponCampaign',
                request_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                _registered_method=True)
        self.getCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getCouponCampaign',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                _registered_method=True)
        self.deleteCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/deleteCouponCampaign',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.listCouponCampaignsDeprecated = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponCampaignsDeprecated',
                request_serializer=io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                _registered_method=True)
        self.listCouponCampaigns = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponCampaigns',
                request_serializer=io_dot_common_dot_filter__pb2.Filters.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                _registered_method=True)
        self.getAnalytics = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getAnalytics',
                request_serializer=io_dot_common_dot_reporting__pb2.AnalyticsRequest.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaignAnalyticsResponse.FromString,
                _registered_method=True)
        self.createCouponOffer = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/createCouponOffer',
                request_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateCouponOffer = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/updateCouponOffer',
                request_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                _registered_method=True)
        self.getCouponOffer = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getCouponOffer',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                _registered_method=True)
        self.deleteCouponOffer = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/deleteCouponOffer',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.listCouponOffersDeprecated = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponOffersDeprecated',
                request_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                _registered_method=True)
        self.listCouponOffers = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponOffers',
                request_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequest.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                _registered_method=True)
        self.createCoupon = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/createCoupon',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateCoupon = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/updateCoupon',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.streamCouponUpdates = channel.stream_stream(
                '/single_use_coupons.SingleUseCoupons/streamCouponUpdates',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.redeemCoupon = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/redeemCoupon',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.updateCouponExternalId = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/updateCouponExternalId',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.CouponNewExternalIdRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.streamCouponRedemptions = channel.stream_stream(
                '/single_use_coupons.SingleUseCoupons/streamCouponRedemptions',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.getCouponById = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getCouponById',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                _registered_method=True)
        self.getCouponByExternalId = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getCouponByExternalId',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.ExternalIdRequest.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                _registered_method=True)
        self.voidCoupon = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/voidCoupon',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.listCouponsByCouponCampaignDeprecated = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponsByCouponCampaignDeprecated',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                _registered_method=True)
        self.listCouponsByCouponCampaign = channel.unary_stream(
                '/single_use_coupons.SingleUseCoupons/listCouponsByCouponCampaign',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                _registered_method=True)
        self.countCouponsByCouponCampaignDeprecated = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/countCouponsByCouponCampaignDeprecated',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.countCouponsByCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/countCouponsByCouponCampaign',
                request_serializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Count.FromString,
                _registered_method=True)
        self.patchPerson = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/patchPerson',
                request_serializer=io_dot_common_dot_personal__pb2.PersonRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.copyCouponCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/copyCouponCampaign',
                request_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CampaignCopyRequest.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                _registered_method=True)
        self.getMetaKeysForCampaign = channel.unary_unary(
                '/single_use_coupons.SingleUseCoupons/getMetaKeysForCampaign',
                request_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
                response_deserializer=io_dot_common_dot_common__objects__pb2.Strings.FromString,
                _registered_method=True)


class SingleUseCouponsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponCampaignsDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponCampaigns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createCouponOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCouponOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCouponOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteCouponOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponOffersDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponOffers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamCouponUpdates(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def redeemCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateCouponExternalId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamCouponRedemptions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCouponById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCouponByExternalId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def voidCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponsByCouponCampaignDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listCouponsByCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countCouponsByCouponCampaignDeprecated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countCouponsByCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def patchPerson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def copyCouponCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetaKeysForCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SingleUseCouponsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.createCouponCampaign,
                    request_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCouponCampaign,
                    request_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            ),
            'getCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.getCouponCampaign,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            ),
            'deleteCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteCouponCampaign,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'listCouponCampaignsDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponCampaignsDeprecated,
                    request_deserializer=io_dot_common_dot_pagination__pb2.Pagination.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            ),
            'listCouponCampaigns': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponCampaigns,
                    request_deserializer=io_dot_common_dot_filter__pb2.Filters.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            ),
            'getAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.getAnalytics,
                    request_deserializer=io_dot_common_dot_reporting__pb2.AnalyticsRequest.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaignAnalyticsResponse.SerializeToString,
            ),
            'createCouponOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.createCouponOffer,
                    request_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateCouponOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCouponOffer,
                    request_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            ),
            'getCouponOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.getCouponOffer,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            ),
            'deleteCouponOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteCouponOffer,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'listCouponOffersDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponOffersDeprecated,
                    request_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequestDeprecated.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            ),
            'listCouponOffers': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponOffers,
                    request_deserializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequest.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            ),
            'createCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.createCoupon,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCoupon,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'streamCouponUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.streamCouponUpdates,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'redeemCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.redeemCoupon,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'updateCouponExternalId': grpc.unary_unary_rpc_method_handler(
                    servicer.updateCouponExternalId,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.CouponNewExternalIdRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'streamCouponRedemptions': grpc.stream_stream_rpc_method_handler(
                    servicer.streamCouponRedemptions,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'getCouponById': grpc.unary_unary_rpc_method_handler(
                    servicer.getCouponById,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            ),
            'getCouponByExternalId': grpc.unary_unary_rpc_method_handler(
                    servicer.getCouponByExternalId,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.ExternalIdRequest.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            ),
            'voidCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.voidCoupon,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'listCouponsByCouponCampaignDeprecated': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponsByCouponCampaignDeprecated,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            ),
            'listCouponsByCouponCampaign': grpc.unary_stream_rpc_method_handler(
                    servicer.listCouponsByCouponCampaign,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.FromString,
                    response_serializer=io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            ),
            'countCouponsByCouponCampaignDeprecated': grpc.unary_unary_rpc_method_handler(
                    servicer.countCouponsByCouponCampaignDeprecated,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'countCouponsByCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.countCouponsByCouponCampaign,
                    request_deserializer=io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Count.SerializeToString,
            ),
            'patchPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.patchPerson,
                    request_deserializer=io_dot_common_dot_personal__pb2.PersonRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'copyCouponCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.copyCouponCampaign,
                    request_deserializer=io_dot_single__use__coupons_dot_campaign__pb2.CampaignCopyRequest.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            ),
            'getMetaKeysForCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.getMetaKeysForCampaign,
                    request_deserializer=io_dot_common_dot_common__objects__pb2.Id.FromString,
                    response_serializer=io_dot_common_dot_common__objects__pb2.Strings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'single_use_coupons.SingleUseCoupons', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('single_use_coupons.SingleUseCoupons', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SingleUseCoupons(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/createCouponCampaign',
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/updateCouponCampaign',
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.SerializeToString,
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getCouponCampaign',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/deleteCouponCampaign',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponCampaignsDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponCampaignsDeprecated',
            io_dot_common_dot_pagination__pb2.Pagination.SerializeToString,
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponCampaigns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponCampaigns',
            io_dot_common_dot_filter__pb2.Filters.SerializeToString,
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaign.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getAnalytics',
            io_dot_common_dot_reporting__pb2.AnalyticsRequest.SerializeToString,
            io_dot_single__use__coupons_dot_campaign__pb2.CouponCampaignAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createCouponOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/createCouponOffer',
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCouponOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/updateCouponOffer',
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.SerializeToString,
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCouponOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getCouponOffer',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteCouponOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/deleteCouponOffer',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponOffersDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponOffersDeprecated',
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequestDeprecated.SerializeToString,
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponOffers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponOffers',
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffersListRequest.SerializeToString,
            io_dot_single__use__coupons_dot_offer__pb2.CouponOffer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/createCoupon',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/updateCoupon',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamCouponUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/single_use_coupons.SingleUseCoupons/streamCouponUpdates',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def redeemCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/redeemCoupon',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateCouponExternalId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/updateCouponExternalId',
            io_dot_single__use__coupons_dot_coupon__pb2.CouponNewExternalIdRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamCouponRedemptions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/single_use_coupons.SingleUseCoupons/streamCouponRedemptions',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCouponById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getCouponById',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCouponByExternalId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getCouponByExternalId',
            io_dot_single__use__coupons_dot_coupon__pb2.ExternalIdRequest.SerializeToString,
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def voidCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/voidCoupon',
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponsByCouponCampaignDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponsByCouponCampaignDeprecated',
            io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.SerializeToString,
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listCouponsByCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/listCouponsByCouponCampaign',
            io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.SerializeToString,
            io_dot_single__use__coupons_dot_coupon__pb2.Coupon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countCouponsByCouponCampaignDeprecated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/countCouponsByCouponCampaignDeprecated',
            io_dot_single__use__coupons_dot_coupon__pb2.ListRequestDeprecated.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countCouponsByCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/countCouponsByCouponCampaign',
            io_dot_single__use__coupons_dot_coupon__pb2.ListRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def patchPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/patchPerson',
            io_dot_common_dot_personal__pb2.PersonRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def copyCouponCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/copyCouponCampaign',
            io_dot_single__use__coupons_dot_campaign__pb2.CampaignCopyRequest.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMetaKeysForCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/single_use_coupons.SingleUseCoupons/getMetaKeysForCampaign',
            io_dot_common_dot_common__objects__pb2.Id.SerializeToString,
            io_dot_common_dot_common__objects__pb2.Strings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
