# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/scheduler/scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io.common import filter_pb2 as io_dot_common_dot_filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cio/scheduler/scheduler.proto\x12\tscheduler\x1a\x16io/common/filter.proto\":\n\x0bListRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x1c\n\x07\x66ilters\x18\x02 \x01(\x0b\x32\x0b.io.FiltersBe\n\x1a\x63om.passkit.grpc.SchedulerZ.stash.passkit.com/io/model/sdk/go/io/scheduler\xaa\x02\x16PassKit.Grpc.Schedulerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io.scheduler.scheduler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.passkit.grpc.SchedulerZ.stash.passkit.com/io/model/sdk/go/io/scheduler\252\002\026PassKit.Grpc.Scheduler'
  _LISTREQUEST._serialized_start=67
  _LISTREQUEST._serialized_end=125
# @@protoc_insertion_point(module_scope)
